# -*- coding: utf-8 -*-
"""Stock_Trading_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QXjDhtHYeVah-hbscSKOximp7eTrijF
"""

import streamlit as st
# Home Page Block
# Application Description in the main home page
def home():
    st.header("Equity Analyzer")
    #image_1 = Image.open('Stock_3.jpeg')
    #st.image(image_1,use_column_width=True)
    st.markdown(
        f"""
            Welcome to the Equity Analyzer. This is an Application for performing
            comprehnsive analysis of a particular stock. The application will provide
            real time Insight on a particular stock, associated industry and its peers
            to aid investment decisions. The Insight
            is generated leveraging both traditional and alternative data. Please use
            the drop down on the left hand side menu to perform the follwoing analysis
            mentioned below. Each analyss will provde addtional capabilities to generate
            user frindly reports to help investment decision.

            * Fundamental Analysis
            * Technical Analysis
            * Portfolio / Investment Optimisation
            * Correlation / Industry Analysis
            * Peer Comparison Analysis
            * Macroeconomic Indicators
            * News Sentiment, Call Report and 10 Q/K Analysis

        """
    )

# Main Application Block
# Side bar option functionality
def app():
    #image_5 = Image.open('Stock_5.jpeg')
    #st.sidebar.image(image_5, caption='', use_column_width=True)
    st.sidebar.title("Navigation")
    stock_element = st.sidebar.selectbox(
        "Choose a Type of Analysis",
        [
            "Home",
            "Fundamental Analysis",
            "Technical Analysis",
            "Portfolio / Investment Optimisation",
            "Correlation / Industry Analysis",
            "Peer Comparison Analysis",
            "Macro Indicators",
            "Alternative Data Analysis"
        ],
    )

    if stock_element == "Home":
        home()

    #if stock_element == "Fundamental Analysis":
        #FundamentalAnalysis()

    #if stock_element == "Alternative Data Analysis":
        #AlternativeData_NLP()


app()